# Load zsh customizations
for f in ~/.zsh/*; do source $f; done

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

# Add ~/bin to PATH
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

eval "$(atuin init zsh)"
