#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load zsh customizations
for f in ~/.zsh/*; do source $f; done

# Add ~/bin and /opt/homebrew/bin to PATH
export PATH="$HOME/bin:/opt/homebrew/bin:$PATH"
