# Load zsh customizations
for f in ~/.zsh/*; do source $f; done

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add ~/bin and /opt/homebrew/bin to PATH
export PATH="$HOME/bin:/opt/homebrew/bin:$PATH"
