#!/bin/zsh
set -e

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Remove all stacks from the Dock
defaults write com.apple.dock persistent-others -array

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Effectively disable the Dock by setting a large auto-hide delay
defaults write com.apple.dock autohide-delay -float 999999999

# Disable top left hot corner
defaults write com.apple.dock wvous-tl-corner -int 0
defaults write com.apple.dock wvous-tl-modifier -int 0

# Disable top right hot corner
defaults write com.apple.dock wvous-tr-corner -int 0
defaults write com.apple.dock wvous-tr-modifier -int 0

# Disable bottom left hot corner
defaults write com.apple.dock wvous-bl-corner -int 0
defaults write com.apple.dock wvous-bl-modifier -int 0

# Disable bottom right hot corner
defaults write com.apple.dock wvous-br-corner -int 0
defaults write com.apple.dock wvous-br-modifier -int 0

killall Dock

echo 'Configured Dock preferences'
